### PR TITLE
[Documentation] Explanation for amount to Readme.md

### LINKED ISSUE #44: Wichtig: Guide zum auslesen des Amounts
Beim Zusammenspiel von Kurs, Steuern und Gebühren kann es ggf. zu Verwirrungen kommen, welche Werte für den `amount` einer Aktivität genommen werden soll.

Nehmen wir folgende Aktivitäten als Beispiel:
image

In T1 dreht sich alles um die Wertpapiere. Die Liste der Aktivitäten soll somit die Beträge darstellen, die den Wert des Wertpapieres wieder spiegeln.

Deshalb gilt:
`price * shares === amount` // true

Bei einem Kauf, zahlt man Gebühren *vor dem Kauf*.
Bei einem Verkauf, zahlt man Gebühren *nach dem Verkauf*.

Und das wiederum bedeutet, dass bei einem Kauf der `amount` Betrag *ohne* Gebühren ist - also Netto. Während der Betrag bei einem Verkauf Brutto ist, da die Gebühren erst danach abgezogen werden.

Beispiel:
comdirect Verkauf
image

Hier muss, da `share * price === amount // true` gilt, der obige Betrag `5201,81` als `amount` geparsed werden.

Trade Republic Marriott Kauf
image

Hier muss ebenfalls der obige Betrag von `548,31` als `amount` geparsed werden. Nur so gilt `share * price === amount // true`.

### Berechnung in T1
Das bedeutet, dass die Netto-Gewinn-Berechnung in T1 nur die Gebühren der Verkäufe berücksichtigt, da diese im Nachhinein abgezogen werden müssen. Gebühren der Käufe sind gar nicht erst Teil des investierten Kapitals.
Im Dropdown, werden jedoch trotzdem alle Gebühren gelistet als Information für den User.

image

Wie man sieht, fehlt hier circa 1€ zwischen Kursgewinn - Gebühren und dem Bruttogewinn. Das ist der 1€ der Kaufgebühr für Marriott war.

Hoffe das macht soweit Sinn - ich wollte hier lediglich etwas Klarheit schaffen, da wir eben einen Bug diesbezüglich in T1 entdeckt hatten (bei der Gewinn-Berechnung, nicht beim PDF parsen)

Viele Grüße

### PR DESCRIPTION
**Pull request by SirGibihm**
Integrated Information from Issue #44 to the readme file which will get lost otherwise. Fix #44

### CODE REVIEW

**Review by dredav — COMMENTED** [review]
We should also add some informations about fxRates, currencies and dividends. Do you want to do this or can I contribute to your PR?

**Comment by SirGibihm** [comment]
Go ahead, I am not quite sure what you want to add exactly but we desperatly need more documentation anways. It might be of high interest to list what can be part of an activity. (Amount, Fee (postive and negativ fees; what do they mean), Tax, Shares, Type (and which types are supportes), Broker, fxRate, foreignCurrency, ISIN, WKN, Company Name etc.

**Comment by dredav** [comment]
I'm working on the activity structure. I'll push this later today or tomorrow.

**Comment by dredav** [comment]
I've added the current state of master to the `docs`. 
>Oh and as we discussed in #280 and #255 a list of the status codes and what they mean.

After implemention the new status codes, I will adjust the documentation.

**Review by SirGibihm — COMMENTED** [review]
Looks good to me! I can't approve this as it is my PR. You have to approve yourself @dredav

**Review by dredav — APPROVED** [review]

**Pull request merged**
