### PR TITLE
[1822direkt] Allow imports of funds redemption PDFs

### PR DESCRIPTION
**Pull request by carstenhag**

### CODE REVIEW

**Comment by carstenhag** [comment]
I feel like the `datetime: '2020-11-24T' + activities[0].datetime.substring(11)` workaround is quite a hack, I found it at comdirect.test.js.

**Comment by dredav** [comment]
@carstenhag Yes. But currently I don't have a better idea to test the datetime field when the time is the current (±1-2 seconds) time of the import for documents without an order time...
When you have a better idea for testing this time thing, feel free to contribute it.

**Comment by carstenhag** [comment]
Giving it a name (and documenting it with that) would help already imo :)

Maybe something like `function getTimeFieldFromDatetime`, but well, I don't know about how JS namings etc

**Comment by carstenhag** [comment]
Or even better, write a test helper/matcher for datetime only. Something like `function checkDateEquals(datetime)` which only checks for the date portion.

**Review by SirGibihm — APPROVED** [review]
Nothing to complain thus approved. Merge incoming!

**Comment by carstenhag** [comment]
Agree and thanks for merging. We can improve the datetime thing sometime else

**Pull request merged**
