### PR TITLE
Add Portfolio Performance import support for users with EN locale

### PR DESCRIPTION
**Pull request by d-a-n**
Currently the PP import works for DE locale only. With this PR the import is refactored to be easily extendable for other locales. Support for EN comes included.

### CODE REVIEW

**Comment by d-a-n** [comment]
@codeofsumit Can you provide sample activities with all the edge cases for the tests? My portfolio is too simple to serve as a good test basis.

**Comment by codeofsumit** [comment]
@d-a-n anbei eine ZIP mit zwei CSV-Dateien eines deutschen Portfolio-Performance Depots

1. Depot File (Käufe, Verkäufe)
2. Verrechnungskonto (Cashflows, daher kommen Dividenden-Zahlungen)

[Archiv.zip](https://github.com/codeofsumit/tresor-import/files/4869961/Archiv.zip)

Wenn man die reinschmeißt, werden Stand heute alle entsprechenden Aktivitäten (Käufe, Verkäufe, Dividenden) rausgezogen - der Rest ignoriert.

Hilft das?

**Comment by d-a-n** [comment]
@codeofsumit Ja, hilft sehr 👍

**Comment by d-a-n** [comment]
@codeofsumit no, they all pass. Also the build on GH has passed. 🤔

Could you provide more details on what exactly is failing?

**Comment by codeofsumit** [comment]
You're right. I had `node 10.x` locally and `flatMap` was unknown. Changed to `node 12.x` and all tests pass 👌

**Pull request merged**
