### PR TITLE
Update for PR: Standalone distributable

### PR DESCRIPTION
**Pull request by dredav**
I've make some changes depending on your PR #129. I've tested it and can use the webpack output in the demo page (also for production).

For dev run `npm start` and for production you need switch the comment in lines https://github.com/dredav/tresor-import/blob/5311c041d8cfb9dfa01e6f0683ce4ebc503a4e86/demo/js/main.js#L4-L7 and then run: `npm run build && npm run demo`

The final fix was to add `libraryTarget: 'umd'` to the output section of webpack config. What did you think @codeofsumit? Did we need more work for publishing the npm library (... yes we need to fix the npm audit...)

### CODE REVIEW

**Comment by codeofsumit** [comment]
This looks great, thanks David! Will try this locally tomorrow in the T1 codebase and see if we can publish to npm with this 👍.

**Comment by codeofsumit** [comment]
Doesn't work for me yet. I get this error when I `npm start`
image

and `location:5000` seems to redirect to `localhost:5000/demo` which throws a 404
image

In the start script, it's `serve demo` so `localhost:5000` should be the demo app already. Not sure where the redirect happens yet - debugging...

**Comment by dredav** [comment]
> Edit: 404 was a caching error.

Oh yes... Access the demo page with localhost leads with me also to an error 🙄  Accessing with IP works fine. I'm not sure how to fix this caching error @codeofsumit ...

**Comment by codeofsumit** [comment]
Alright so I'm currently getting the `window is not defined` error due to nuxt and server-side tech. I'm trying to work around this from a framework side but if the library would not rely on window (or simply return empty values if window is undefined) that would also make this more compatible with frameworks

**Comment by codeofsumit** [comment]
Habs zum laufen bekommen 👏  - werde diesen branch jetzt auf npm publishen und via npm testen. Wenn alles tut, merge ich 👍

**Comment by codeofsumit** [comment]
Alright, can you change the usage section in the README from `tresor-import` to `@tresor.one/import` ?
Some troll blockt all possible npm names so we had to go with scoped packages, which is actually better. Thanks troll 🤷

**Comment by codeofsumit** [comment]
Hier kann der Import auf Tresor One getestet werden - installiert durch npm:
https://t1-git-move-import-to-npm.ofsumit.vercel.app/

Gerne einmal was reinwerfen, auch CSV von PP 👍 .
Wenns bei euch tut, mergen wir sobald die README noch angepasst ist 🎉

**Comment by dredav** [comment]
@codeofsumit I adjusted the README file. The import works for me with an PP example and some comdirect documents.

**Comment by dredav** [comment]
@codeofsumit How did you solve the `window is not defined` issue? Have you created a "nuxt plugin" and set `ssr` to `false?`?

**Comment by codeofsumit** [comment]
I put the import statement into a component and that component is wrapped in clientOnly. The import of the component instance is also conditionally only when process.client is true

**Pull request merged**
