### PR TITLE
[traderepublic] Parse the quarter / year statement as buy activities

### LINKED ISSUE #98: [traderepublic] Allow import of quarter statement
The quarter statement contains a lot of information for import the current portfolio.
The fees and taxes are missing but we can ignore them for an "easy import". The user can enter it later manually.
See also: https://community.tresor.one/c/help/probleme-mit-import#comment_175867

### PR DESCRIPTION
**Pull request by dredav**
- This PR requires the merge of #99 first.
- This PR will fix #98 
- Add multi-page support for trade republic
- Add multi-activity per page support
- Adjust existing mock files
- Add logic to parse the quarter / year statement as buy activities

### CODE REVIEW

**Comment by dredav** [comment]
I'm not sure why github ignores the `git mv` command for renaming existing mock files 😞

**Comment by dredav** [comment]
@codeofsumit Conflict is resolved

**Comment by codeofsumit** [comment]
Damn there are conflicts again

**Comment by dredav** [comment]
@codeofsumit I will fix this after dinner

**Comment by dredav** [comment]
So, again ready to merge @codeofsumit 😆

**Pull request merged**
