### PR TITLE
Add consorsbank support

### LINKED ISSUE #2: Consorsbank Support
Issue für Consorsbank Support.
Benötige noch Test PDFs - bitte an sumit@tresor.one schicken

### PR DESCRIPTION
**Pull request by felixheck**
Fixes #2

### CODE REVIEW

**Comment by d-a-n** [comment]
Hey @felixheck,

awesome, thanks 🎉 

Would you mind adding some tests?

**Comment by felixheck** [comment]
Hey @d-a-n,
I'll try to add them today or tomorrow

**Comment by felixheck** [comment]
@d-a-n  here you go 😉

**Comment by d-a-n** [comment]
@felixheck great, thanks 👍 

LGTM

I guess this PR is ready to be merged @codeofsumit

**Comment by codeofsumit** [comment]
All my test PDFs worked like a charm 👏 👏 
Well done 🎉

**Pull request merged**
